### ISSUE TITLE
ジョブ成功した際のSuccess情報送信ログ内容について

### ISSUE THREAD

**Issue by sawadyrr5** [nrck/KotoriAgent#4]
同じshを実行するジョブ001と002を直列に実行するようにnextMatrixを定義したとき、kotoriのログに以下のように出力されました。

```
1|kotori  | [2018-10-15 21:22:03]ws://127.0.0.1:27131/に接続を開始しました。
1|kotori  | [2018-10-15 21:22:04]ws://127.0.0.1:27131/に接続しました。
1|kotori  | [2018-10-15 21:22:04]サーバ認証に成功しました。
1|kotori  | [2018-10-15 21:24:00]file:/home/pi/jobnets/testjob.sh, args:undefined, cwd:/home/pi/jobnets/
1|kotori  | [2018-10-15 21:24:00]ジョブを実行しました。（execFile：/home/pi/jobnets/testjob.sh、PID：23229）
1|kotori  | [2018-10-15 21:24:00]onExecSuccessが実行されました。
1|kotori  | [2018-10-15 21:24:00]サーバにタイプSendJobResult、シリアル5、ジョブコード001を送信しました。
1|kotori  | [2018-10-15 21:24:00]stdout=hello world!
1|kotori  | , stderr=
1|kotori  | [2018-10-15 21:24:00]ジョブが成功しました。（execFile：/home/pi/jobnets/testjob.sh、RC：0）
1|kotori  | [2018-10-15 21:24:00]シリアル：5, ジョブコード001のSuccess情報送信が受理されました。
1|kotori  | [2018-10-15 21:25:00]file:/home/pi/jobnets/testjob.sh, args:undefined, cwd:/home/pi/jobnets/
1|kotori  | [2018-10-15 21:25:00]ジョブを実行しました。（execFile：/home/pi/jobnets/testjob.sh、PID：23239）
1|kotori  | [2018-10-15 21:25:00]onExecSuccessが実行されました。
1|kotori  | [2018-10-15 21:25:00]サーバにタイプSendJobResult、シリアル5、ジョブコード002を送信しました。
1|kotori  | [2018-10-15 21:25:00]stdout=hello world!
1|kotori  | , stderr=
1|kotori  | [2018-10-15 21:25:00]ジョブが成功しました。（execFile：/home/pi/jobnets/testjob.sh、RC：0）
1|kotori  | [2018-10-15 21:25:00]シリアル：5, ジョブコード002のSuccess情報送信が受理されませんでした。
```

ジョブ001が成功して、
```
1|kotori  | [2018-10-15 21:24:00]シリアル：5, ジョブコード001のSuccess情報送信が受理されました。
```
という出力なのであれば、ジョブ002が成功した場合に
```
1|kotori  | [2018-10-15 21:25:00]シリアル：5, ジョブコード002のSuccess情報送信が受理されませんでした。
```
というログ出力は想定どおりでしょうか？

**Comment by nrck** [comment]
報告ありがとうございます。
ジョブ自体は成功していますが、何らかの理由によりPoplarServerでsuccess情報が書き込めていないようです。
原因究明のため、同時刻体のPoplaserverのログも併せて添付お願いします。

**Comment by sawadyrr5** [comment]
よろしくおねがいします。
[poplar-stdout.log](https://github.com/nrck/KotoriAgent/files/2478857/poplar-stdout.log)
[poplar-stderr.log](https://github.com/nrck/KotoriAgent/files/2478863/poplar-stderr.log)

**Comment by nrck** [comment]
ありがとうございます。
ログ上は問題なさそうですね。

終了状態を確認したいので、poplarserver のlogフォルダ配下のファイルを添付してもらえますでしょうか？

**Comment by sawadyrr5** [comment]
こちらです。
ジョブが想定どおりに実行されるかどうか確認するため、何度かjobnet.jsonの内容を変えてupload->pm2 restart allしましたが、ジョブネット名は変えてませんでした。

[runjobnet.zip](https://github.com/nrck/KotoriAgent/files/2478910/runjobnet.zip)

**Comment by nrck** [comment]
runjobnet.jsonの記録だと、jobcode 002は正常に終わっていてます。
しかし、endジョブがうまく叩けていないようです。
少し調査を進めてみます。

**Comment by nrck** [comment]
https://github.com/nrck/PoplarServer/blob/e80c593edb7d89ce0d5d1f671adb30f0d4156746/src/jobscheduler.ts#L682

現在のjobnetだと、ここでundefined Exceptionになる見込みです。
それを以下でcatchし、受理しなかった（ack(false)を返した）と推測します。

https://github.com/nrck/PoplarServer/blob/e80c593edb7d89ce0d5d1f671adb30f0d4156746/src/app.ts#L76

現状仕様通りの動きとなっています。（isSpecialフラグの意味…は置いといて）
回避策は「end jobにもschedule設定を入れる」です。よろしくおねがいします。

**Comment by sawadyrr5** [comment]
なるほどありがとうございます。endジョブにもschedule.startを入れた結果、現象が抑止されることが確認できました。
